### ISSUE TITLE
Timing 渲染时若 BPM 过高可能会导致崩溃

### ISSUE THREAD

**Issue by JoinChang** [Arcaea-Infinity/ArcaeaChartRender#1]
测试报错语句：
```
timing(19058,255000.00,3.00);
```

报错内容：
```python
Traceback (most recent call last):
  ...
  File "...\render.py", line 162, in __init__
    self._render()
  File "...\render.py", line 171, in _render
    self._draw_variable_speed_layer()
  File "...\render.py", line 253, in _draw_variable_speed_layer
    draw.rectangle(
  File "C:\Users\Lxns\AppData\Roaming\Python\Python311\site-packages\PIL\ImageDraw.py", line 294, in rectangle
    self.draw.draw_rectangle(xy, fill, 1)
ValueError: y1 must be greater than or equal to y0
```

**Comment by zhanbao2000** [comment]
Pillow 9.5.0 中新增了对 `ImageDraw` 的坐标顺序限制，参考：

[Raise an error if ImageDraw co-ordinates are incorrectly ordered](https://github.com/python-pillow/Pillow/pull/6978)

已于 [3deb383](https://github.com/Arcaea-Infinity/ArcaeaChartRender/commit/3deb3831c746bbb07c448f90f215afd25a2e59a1) 修复
